Models/Cart.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Souq.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public DateTime? DateTime { get; set; }
        public float? Price { get; set; }
        public float? TotalPrice { get; set; }
        public int? Quentity { get; set; }
        public string? UserID { get; set; }

        [ForeignKey("product")]
        public int? ProductId { get; set; }
        //public string Image { get; set; }
        public Product? product { get; set; }
    }
}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Souq.Data;
using Souq.Models;

namespace Souq.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Carts.Include(c => c.product).Where(x => x.UserID == User.Identity.Name);
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpGet]
        public IActionResult GoFormOrder()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddOrder(Order order)
        {
            Order o = new Order { 
                Email = order.Email,
                Address = order.Address,
                Name = order.Name,
                PhoneNumber = order.PhoneNumber,
                UserID = User.Identity.Name
            };
            //عشان افضي السلة 
            var CartItem=_context.Carts.Where(x=> x.UserID == User.Identity.Name).ToList();
            _context.Carts.RemoveRange(CartItem);
            _context.Order.Add(o);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
   
        public IActionResult AddProductToCart(int id)
        {
            var price = _context.Products.Find(id).Price;
            var item =_context.Carts.FirstOrDefault(x => x.ProductId == id && x.UserID ==User.Identity.Name);
            if(item != null)
            {
                item.Quentity += 1;
                item.TotalPrice = price * item.Quentity;
                item.Price = price;
            }
            else
            {
                _context.Carts.Add(new Cart
                {
                    ProductId = id,
                    Price = price ,
                    UserID = User.Identity.Name,
                    Quentity=1,
                    TotalPrice = price,
                    DateTime = DateTime.Now,
                });
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult GetSingleProductByCategoryID(int id)
        {
            //ViewBag.cate = _context.Categories.FirstOrDefault(x => x.Id == id);
            var product = _context.Carts.Include(x=> x.product).ThenInclude(v=>v.category.Name).FirstOrDefault(c=> c.Id== id);
            return View(product);
        }
        // GET: Carts/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateTime,Price,Quentity,UserID,ProductId")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", cart.ProductId);
            return View(cart);
        }

        // GET: Carts/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", cart.ProductId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateTime,Price,Quentity,UserID,ProductId")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", cart.ProductId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carts'  is null.");
            }
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                _context.Carts.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
          return (_context.Carts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Carts/Create.cshtml
@model Souq.Models.Cart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quentity" class="control-label"></label>
                <input asp-for="Quentity" class="form-control" />
                <span asp-validation-for="Quentity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <input asp-for="UserID" class="form-control" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carts/Delete.cshtml
@model Souq.Models.Cart

@{
    ViewData["Title"] = "Delete";
}
<div class="page-header" style="background: url(assets/img/banner1.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Carts</h2>
              
                </div>
            </div>
        </div>
    </div>
</div>


<section class="featured section-padding">
    <div class="container">
        <h1 class="section-title"> Delete Items</h1>
        <h3>Are you sure you want to delete this Item?</h3>
        <div class="row">

      
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4" style="margin-left:400px">
                 
                    <div class="featured-box">
                    <figure>


                        <a href="#"><img class="img-fluid" src="~/Imgs/@Model.product.Image" alt=""></a>
                    </figure>
                        <div class="feature-content">
                           
                            <h4><a href="ads-details.html"> </a></h4>
                            <div class="meta-tag">
                                <span>
                                <a href="#"><i class="lni-user"></i>              @Html.DisplayFor(model => model.UserID)</a>
                                </span>
                                <span>
                                <a href="#"><i class="lni-map-marker"></i>     @Html.DisplayFor(model => model.DateTime)</a>
                                </span>
                                <span>
                                <a href="#"><i class="lni-tag"></i>  @Html.DisplayFor(model => model.Quentity) Pieces</a>
                                </span>
                            </div>
                        <p class="dsc">             @Html.DisplayFor(model => model.product.Description)</p>
                            <div class="listing-bottom">
                            <h3 class="price float-left">$@Html.DisplayFor(model => model.TotalPrice)</h3>


                            </div>
                        </div>

                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-action="Index" class="btn btn-common">Back </a>
                    </form>
                    </div>
                </div>
            
        </div>
    </div>
</section>

Views/Carts/Details.cshtml
@model Souq.Models.Cart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quentity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quentity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-common btn-filters" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-common btn-filters">Back to List</a>
</div>
<br />
<br />
 <section class="featured section-padding">
    <div class="container">
        <h1 class="section-title">Product Details</h1>
        <div class="row">
            
           
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
                    <div class="featured-box">
                    <a><span class="price">$@Html.DisplayFor(model => model.Price)</span></a>
                        <div class="feature-content">
                            <div class="product">
                            <a href="#">@Html.DisplayFor(model => model.product.CategoryId) </a>
                                
                            </div>
                        <h4><a href="ads-details.html">@Html.DisplayFor(model => model.product.Name)</a></h4>
                        
                            <div class="meta-tag">
                                <span>
                                <a href="#"><i class="lni-user"></i> @Html.DisplayFor(model => model.Quentity) Piece</a>
                                </span>
                                <span>
                                <a href="#"><i class="lni-map-marker"></i> @Html.DisplayFor(model => model.DateTime)</a>
                                </span>
                                <span>
                                    <a href="#"><i class="lni-tag"></i> Canon</a>
                                </span>
                            </div>
                        <p class="dsc">@Html.DisplayFor(model => model.product.Description)</p>
                            <div class="listing-bottom">
                            <h3 class="price float-left">$ @Html.DisplayFor(model => model.TotalPrice)</h3>
                              

                            </div>
                        </div>
                    </div>
                <div>
                    <a asp-action="Edit" class="btn btn-common btn-filters" asp-route-id="@Model?.Id">Edit</a> |
                    <a asp-action="Index" class="btn btn-common btn-filters">Back to List</a>
                </div>
                </div>
            
        </div>
    </div>
</section> 
<br />
<br />

Views/Carts/Edit.cshtml
@model Souq.Models.Cart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quentity" class="control-label"></label>
                <input asp-for="Quentity" class="form-control" />
                <span asp-validation-for="Quentity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <input asp-for="UserID" class="form-control" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carts/GoFormOrder.cshtml
<div class="page-header" style="background: url(assets/img/banner1.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Make Order</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Home /</a></li>
                        <li class="current">Make Order</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="content" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-xs-12">

                <form asp-action="AddOrder" asp-controller="Carts" method="post" class="contact-form">
                    <h2 class="contact-title">
                       Order Informations
                    </h2>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="Name" name="Name" placeholder="Name" required="" data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <input type="email" class="form-control" id="Email" name="Email" placeholder=" Email" required="" data-error="Please enter your email">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="Address" name="Address" placeholder="Address" required="" data-error="Please enter your Address">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-4">
                            <div class="form-group">
                                <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber" placeholder="PhoneNumber" required="" data-error="Please enter your PhoneNumber">
                                <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" onclick="alert('Send sucsess')" id="submit" class="btn btn-common " style="pointer-events: all; cursor: pointer;">Submit Now</button>
                            <div id="msgSubmit" class="h3 text-center hidden"></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </form>
            </div>
          

Views/Carts/Index.cshtml
@model IEnumerable<Souq.Models.Cart>

@{
    ViewData["Title"] = "Index";
}

<div class="page-header" style="background: url(assets/img/banner1.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Carts</h2>
                    <ol class="breadcrumb">
                        <li><a href="/Home/index">Home /</a></li>
                        <li class="current">Carts</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
@* 
<p>
    <a asp-action="Create">Create New</a>
</p>*@

</table>
<section class="featured section-padding">
    <div class="container">
        <span class="btn btn-common io" style="background-color:#555555">All Price :$@Model.Sum(item => item.TotalPrice)</span>
        <h1 class="section-title"> My Items</h1>
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
                    <a><span class="price">$@Html.DisplayFor(model => item.Price)</span></a>
                    <div class="featured-box">
                        <figure>
                        

                            <a href="#"><img class="img-fluid" src="~/Imgs/@item.product.Image" alt=""></a>
                        </figure>
                        <div class="feature-content">
                            <div class="product">
                                <a href="#">Electronic &gt; </a>
                                <a href="#">Cameras</a>
                            </div>
                            <h4><a href="ads-details.html"> @Html.DisplayFor(modelItem => item.product.Name)</a></h4>
                            <div class="meta-tag">
                                <span>
                                    <a href="#"><i class="lni-user"></i>  @Html.DisplayFor(modelItem => item.UserID)</a>
                                </span>
                                <span>
                                    <a href="#"><i class="lni-map-marker"></i>   @Html.DisplayFor(modelItem => item.DateTime)</a>
                                </span>
                                <span>
                                    <a href="#"><i class="lni-tag"></i>  @Html.DisplayFor(modelItem => item.Quentity) Pieces</a>
                                </span>
                            </div>
                            <p class="dsc"> @Html.DisplayFor(modelItem => item.product.Description)</p>
                            <div class="listing-bottom">
                                <h3 class="price float-left">$@item.TotalPrice</h3>
                              

                            </div>
                        </div>
                            <a asp-action="Delete" class="btn btn-common btn-filters" asp-route-id="@item.Id">Delete</a>
                    
                    </div>
                </div>
            }
          
        </div>
        <a href="/Carts/GoFormOrder" class="btn btn-common io" type="submit" style="margin-left:500px; background-color:#555555; font-weight:bold">  Order</a>
        
    </div>

</section>
<a asp-action="Index" asp-controller="Home" class="btn btn-common" style="margin-left:50px;">Back </a>